### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by sonvirgo** [hkociemba/FifteenPuzzle#2]
Do you confirm that pattern database can solve ‘devil configuration?
1 5 9 13
2 6 10 14
3 7 11 15
4 8 12

Does it work consistently in time and step taken if you try it several time? In average how much time and how many steeps to reach the final goal state?

**Comment by sonvirgo** [comment]
My assessment, BFS or any path finding algorithms is suitable for linear approximation. Like how the cost have been calculated. In general, It may be applicable to b puzzle which is not a linear problem. Unfortunately, some BFS code show some success in some set of N puzzle problem. may be this sub set is only a linear sub set of all possible permutation. That why for non linear or very special configuration, all path finding algorithm failed. Some one have found or have inferred to the one of the initial configuration as the above. I have tested it in many real code and it stuck going from node to node, the taxi cab fluctuate down then up then down then up and almost never reach goal.

**Comment by sonvirgo** [comment]
I have a small suggestion for you.
As I said earlier, when you use any path finding algorithm to traverse the node tree, the adjacent node has smaller taxicab than initial node. But the fact is that all pieces of N-puzzle are correlated. So if you move one piece closer to its correct position to gain better cost, probable you move other piece further its correct  position. So instead of just simple re-calculate the cost when you create a new node. I suggest you make another calculation to ensure all pieces go closer to their corresponding correct position.  This way, it will cost you more processing resources but eliminating invaluable node and fluctuation, also ensure 100% success rate on time.

**Comment by hkociemba** [comment]
> Do you confirm that pattern database can solve ‘devil configuration?
> 1 5 9 13
> 2 6 10 14
> 3 7 11 15
> 4 8 12
> 
> Does it work consistently in time and step taken if you try it several time? In average how much time and how many steeps to reach the final goal state?

With the 78 pattern database enabled it finds the optimal 72 step solution in 11.2 s generating 80,581,681 nodes. It does not matter if you try it several times - it is always the same.

**Comment by sonvirgo** [comment]
So, special case need special care, congrats and thank you

**Comment by sonvirgo** [comment]
how about blank cell random instead of upper left or lower right?

**Comment by hkociemba** [comment]
> how about blank cell random instead of upper left or lower right?
No good idea. With the blank cell in the lower right or upper left you can use the same pruning tables since these two goal positions are related by a a 180° rotation together with a number transformation x  -> 16 - x.
For other positions of the blank you would have to recalculate the pruning tables.

**Comment by sonvirgo** [comment]
> > how about blank cell random instead of upper left or lower right?
> > No good idea. With the blank cell in the lower right or upper left you can use the same pruning tables since these two goal positions are related by a a 180° rotation together with a number transformation x  -> 16 - x.
> > For other positions of the blank you would have to recalculate the pruning tables.

good idea for gamers not for silvers :D 
same as pattern database solution, more like traversing 500Mb database than an Intelligent solution
thank you however
